# default configuration file

# general
facility: 'local'
engine: 'local'
raw_data_dir: ''

detector_distance: 100  # in mm
pixel_size: 100  # in um
image_height: 1000  # in pixel
image_width: 1000  # in pixel
center_x: 500 # in pixel
center_y: 500 # in pixel
photon_energy: 9000  # in eV

compress_raw_data: false
raw_dataset: ''
compressed_batch_size: 100
compressed_dataset: ''
cheetah_datasets: ''
curr_hit_tag: null
cxi_entry_id: 1
cxi_size: 100
job_pool_size: 3
max_info: 1000
min_peaks: 15
min_max_intensity: 0
mpi_batch_size: 5
update_period: 5  # in sec
