# default configuration file

# general
facility: 'local'
engine: 'local'
raw_data_directory: ''

detector_distance: 100  # in mm
pixel_size: 100  # in um
image_height: 1000  # in pixel
image_width: 1000  # in pixel
center_x: 500 # in pixel
center_y: 500 # in pixel